CREATE TABLE Student (
  ID VARCHAR2(9),
  Name VARCHAR2(20),
  Department VARCHAR2(3),
  DateOfBirth DATE,
  Phone VARCHAR2(11),
  Email VARCHAR2(255),
  CONSTRAINT PK_Student PRIMARY KEY (ID)
);

CREATE TABLE Nurse (
  ID VARCHAR2(9),
  Name VARCHAR2(20),
  Phone VARCHAR2(11),
  Email VARCHAR2(255),
  StartTime DATE,
  EndTime DATE,
  Salary NUMBER(10, 5),
  CONSTRAINT PK_Nurse PRIMARY KEY (ID)
);

CREATE TABLE Doctor (
  ID VARCHAR2(9),
  Name VARCHAR2(20),
  Specialization VARCHAR2(20),
  Phone VARCHAR2(11),
  Email VARCHAR2(255),
  StartTime DATE,
  EndTime DATE,
  CONSTRAINT PK_Doctor PRIMARY KEY (ID)
);

CREATE TABLE Visit (
  SID VARCHAR2(9),
  VID VARCHAR2(9),
  VDate DATE,
  VTime DATE,
  CONSTRAINT PK_Visit PRIMARY KEY (VID),
  CONSTRAINT FK_Visit_SID FOREIGN KEY (SID) REFERENCES Student(ID)
);

CREATE TABLE Attend (
  NurseID VARCHAR2(9),
  DoctorID VARCHAR2(9),
  VID VARCHAR2(9),
  AttendID VARCHAR2(9),
  CONSTRAINT PK_Attend PRIMARY KEY (AttendID),
  CONSTRAINT FK_Attend_NurseID FOREIGN KEY (NurseID) REFERENCES Nurse(ID),
  CONSTRAINT FK_Attend_DoctorID FOREIGN KEY (DoctorID) REFERENCES Doctor(ID),
  CONSTRAINT FK_Attend_VID FOREIGN KEY (VID) REFERENCES Visit(VID)
);

CREATE TABLE Prescription (
  AttendID VARCHAR2(9),
  Pcomment VARCHAR2(30),
  PID VARCHAR2(9),
  CONSTRAINT PK_Prescription PRIMARY KEY (AttendID),
  CONSTRAINT FK_Prescription_PID FOREIGN KEY (PID) REFERENCES Attend(AttendID)
);

CREATE TABLE Medicine (
  MedID VARCHAR2(9),
  Name VARCHAR2(20),
  Generic VARCHAR2(20),
  Producer VARCHAR2(20),
  CONSTRAINT PK_Medicine PRIMARY KEY (MedID)
);

CREATE TABLE Test (
  TestID VARCHAR2(9),
  Name VARCHAR2(20),
  Fee NUMBER(10, 5),
  CONSTRAINT PK_Test PRIMARY KEY (TestID)
);

CREATE TABLE PresMed (
  MedID VARCHAR2(9),
  PID VARCHAR2(9),
  PMcomment VARCHAR2(20),
  CONSTRAINT PK_PresMed PRIMARY KEY (MedID, PID),
  CONSTRAINT FK_PresMed_PID FOREIGN KEY (PID) REFERENCES Prescription(AttendID),
  CONSTRAINT FK_PresMed_MedID FOREIGN KEY (MedID) REFERENCES Medicine(MedID)
);

CREATE TABLE PresTest (
  PID VARCHAR2(9),
  TestID VARCHAR2(9),
  PTcomment VARCHAR2(30),
  CONSTRAINT PK_PresTest PRIMARY KEY (PID, TestID),
  CONSTRAINT FK_PresTest_TestID FOREIGN KEY (TestID) REFERENCES Test(TestID),
  CONSTRAINT FK_PresTest_PID FOREIGN KEY (PID) REFERENCES Prescription(AttendID)
);

CREATE TABLE Referance (
  AttendID VARCHAR2(9),
  RefComment VARCHAR2(30),
  RID VARCHAR2(9),
  CONSTRAINT PK_Referance PRIMARY KEY (RID),
  CONSTRAINT FK_Referance_AttendID FOREIGN KEY (AttendID) REFERENCES Attend(AttendID)
);

CREATE TABLE Bill (
  RID VARCHAR2(9),
  Amount NUMBER(10, 5),
  BillID VARCHAR2(9),
  CONSTRAINT PK_Bill PRIMARY KEY (BillID),
  CONSTRAINT FK_Bill_RID FOREIGN KEY (RID) REFERENCES Referance(RID)
);
